### PR TITLE
Fix projections on GRCh38

### LINKED ISSUE #474: Bug: problem with projection! in jannovar-cli-033.jar
I get an error with the following variant in hg19 assembly:

##fileformat=VCFv4.1
##contig=<ID=1,length=249250621>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	individual
13	114435823	.	T	G	431.31	.	.	GT:AD:DP:GQ:PL	0/1:17,10:27:21:21,0,395

The error:

Options
JannovarAnnotateVCFOptions [escapeAnnField=true, pathInputVCF=ClinPrior.vcf, interval=, pathOutputVCF=outputJannovar.vcf, pathVCFDBSNP=null, prefixDBSNP=DBSNP_, pathFASTARef=null, pathVCFExac=null, prefixExac=EXAC_, pathVCFGnomadExomes=null, prefixGnomadExomes=GNOMAD_EXOMES_, pathVCFGnomadGenomes=null, prefixGnomadGenomes=GNOMAD_GENOMES_, pathVCFUK10K=null, prefixUK10K=UK10K_, pathThousandGenomes=null, prefixThousandGenomes=G1K_, pathClinVar=null, prefixClinVar=CLINVAR_, pathCosmic=null, prefixCosmic=COSMIC_, pathPedFile=null, annotateAsSingletonPedigree=false, useThresholdFilters=false, useAdvancedPedigreeFilters=false, threshFiltMinGtCovHet=8, threshFiltMinGtCovHomAlt=4, threshFiltMaxCov=10000, threshFiltMinGtGq=20, threshFiltMinGtAafHet=0.2, threshFiltMaxGtAafHet=0.8, threshFiltMinGtAafHomAlt=0.7, threshFiltMaxGtAafHomRef=0.3, threshFiltMaxExacHomAlt=20, threshFiltMaxThousandGenomesHomAlt=10, threshFiltMaxAlleleFrequencyAd=0.01, threshFiltMaxAlleleFrequencyAr=0.01, offTargetFilterEnabled=false, offTargetFilterUtrIsOffTarget=false, offTargetFilterIntronicSpliceIsOffTarget=false, oneParentGtFilteredFiltersAffected=false, inheritanceAnnoUseFilters=false, useParentGtIsFiltered=true, threshDeNovoParentAd2=1, bedAnnotationOptions=[], dbNsfpColContig=1, dbNsfpColPosition=2, prefixDbNsfp=DBNSFP_, pathDbNsfp=null, columnsDbNsfp=[], tsvAnnotationOptions=[], vcfAnnotationOptions=[]]
Deserializing transcripts...
INFO Deserializing JannovarData from C:/Users/aschluter.IDIBELL1573/Documents/R/win-library/3.6/ClinPrior/extdata/Jannovar/hg19_refseq.ser
INFO Deserialization took 7,37 sec.
Location	processed.sites	runtime.per.1M.sites	completed	total.runtime	remaining
Annotating VCF...
Will read full input file
Exception in thread "main" java.lang.Error: Bug: problem with projection!
	at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:117)
	at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:287)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:400)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:337)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:296)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:411)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
Caused by: de.charite.compbio.jannovar.reference.ProjectionException: Invalid transcript sequence position 1302
	at de.charite.compbio.jannovar.reference.TranscriptProjectionDecorator.transcriptToGenomePos(TranscriptProjectionDecorator.java:169)
	at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:113)
	... 15 more
[1] 1

### LINKED ISSUE #524: Problems with projection of dbSNP variants and RefSeq for hg38
**Describe the bug**
Jannovar crashes for some variants for hg38 and RefSeq. This is the collection ticket for dbSNP positions.

**To Reproduce**
Run with Jannovar 0.36-SNAPSHOT and data release candidate.

**Expected behavior**
Jannovar should not crash as all errors should be properly handled and annotated.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by holtgrewe**
closes #474 
closes #524

### CODE REVIEW

**Comment by holtgrewe** [comment]
Merge is pending running dbSNP through ensembl and refseq GRCh38

File: jannovar-core/src/main/java/de/charite/compbio/jannovar/reference/TranscriptProjectionDecorator.java [hunk 1]
```diff
@@ -166,7 +166,7 @@ public GenomePosition transcriptToGenomePos(TranscriptPosition pos) throws Proje
 		if (targetSeqPos < 0) {
 			throw new ProjectionException("Invalid transcript sequence position " + targetSeqPos);
 		} else if (targetSeqPos
-			> Anchors.seqLength(transcript.getSeqAlignment().getRefAnchors()) + 1) {
```
Comment (holtgrewe) [inline jannovar-core/src/main/java/de/charite/compbio/jannovar/reference/TranscriptProjectionDecorator.java:169]: This is the fix!
